### ISSUE TITLE
installing to a custom path

### ISSUE THREAD

**Issue by andrei-pavel** [CESNET/libyang-cpp#1]
Hello!

When installing sysrepo from sources, I am able to have libyang installed in a custom path by providing this command:
```
cmake -DLIBYANG_INCLUDE_DIR="/opt/libyang/include" -DLIBYANG_LIBRARY="/opt/libyang/lib/libyang.so"
```
This doesn't seem to be an option for libyang-cpp and libsysrepo-cpp. Could this be done?

My goal is to have all four repos installed in custom paths, so that they can be easily uninstalled without `make uninstall` which requires the user to have access to the sources.

Thanks!

**Comment by syyyr** [comment]
Hi,

it is possible to install libyang-cpp in a custom path by using the `CMAKE_INSTALL_PREFIX` variable. So, in your case, your cmake invocation would look something like this:
```
cmake -DCMAKE_INSTALL_PREFIX="/opt/libyang-cpp"
```
Let me know, if you have any more questions.

**Comment by andrei-pavel** [comment]
```
-- Checking for modules 'libyang>=2.0.7;libyang'
--   Package 'libyang', required by 'virtual:world', not found
--   Package 'libyang', required by 'virtual:world', not found
CMake Error at /usr/share/cmake-3.21/Modules/FindPkgConfig.cmake:562 (message):
A required package was not found
```
It can't find /opt/libyang.

**Comment by syyyr** [comment]
This is more of a cmake problem, then libyang/libyang-cpp problem, but if you installed libyang in a non-standard location, you need to tell cmake where libyang is. If you installed libyang with this command:
```
cmake -DLIBYANG_INCLUDE_DIR="/opt/libyang/include" -DLIBYANG_LIBRARY="/opt/libyang/lib/libyang.so"
```
then it should be enough to set the `CMAKE_PREFIX_PATH` variable to `/opt/libyang` when invoking cmake for libyang-cpp. We are using pkg-config to find libyang.

**Comment by andrei-pavel** [comment]
That's the problem I'm facing. Those commands don't work. Taking inspiration from [sysrepo](https://github.com/sysrepo/sysrepo/blob/a6d470363a5438c0c817f4f13729caa310f5fbce/CMakeLists.txt#L285-L286), I think libyang-cpp needs these lines in CMakeLists.txt:
```
target_link_libraries(libyang-cpp ${LIBYANG_LIBRARIES})
include_directories(${LIBYANG_INCLUDE_DIRS})
```

**Comment by syyyr** [comment]
libyang is linked to libyang-cpp through pkg-config. That means that as long as pkg-config knows where libyang is, then libyang-cpp will also know where it is. So it all comes down to whether it does know, or does not. One way to debug pkg-config is to use this command:
```
pkg-config libyang --libs
```
If this gives an error, you need to tell pkg-config where libyang is. There are two options.
1) point the `PKG_CONFIG_PATH` enviromental variable to your libyang prefix when invoking cmake
2) if your cmake is new enough (version 3.1), set the `CMAKE_PREFIX_PATH` to the install prefix of libyang and cmake should append this path to `PKG_CONFIG_PATH` automatically.

**Comment by andrei-pavel** [comment]
Thanks much!
