### ISSUE TITLE
Version bumped to 2.175

### ISSUE THREAD

**Issue by ayou0057** [CESNET/libyang-cpp#10]
Hello,

The latest version for libyang is https://github.com/CESNET/libyang/releases/tag/v2.1.55, why was the min version bumped to v2.1.75.

Thanks,

**Comment by jktjkt** [comment]
Our `master` branch tracks the upstream libyang `devel` branch; it's just a different naming convention for some technical reasons. Right now the [`devel` branch of libyang is marked as `2.1.79`](https://github.com/CESNET/libyang/blob/devel/CMakeLists.txt#L61) and we require `2.1.76`.
