### ISSUE TITLE
pkg_check_modules fails

### ISSUE THREAD

**Issue by tbsuht** [CESNET/libyang-cpp#13]
https://github.com/CESNET/libyang-cpp/blob/master/CMakeLists.txt#L30

I can't find a released version 2.1.88 for libyang. Is this supposed to mean 2.1.80?

**Comment by syyyr** [comment]
Hello, please use the `devel` branch of _libyang_. It has the newer version.

**Comment by jktjkt** [comment]
Indeed; we're tracking the `devel` branch because of important fixes that these C++ bindings depend on.
