### ISSUE TITLE
lyd_new_term() wrapper

### ISSUE THREAD

**Issue by mcindrich** [CESNET/libyang-cpp#15]
We'd like to convert something along the lines of the following C code into C++ by using libyang-cpp:

```C
ly_err = lyd_new_term(ly_node, ly_uv4mod, "destination-prefix", prefix_buffer, false, NULL);
if (ly_err != LY_SUCCESS) {
  goto error_out;
}
```

Is there an equivalent function for creating a new term, the same way as in using `lyd_new_term()` in the C library where a different module can be provided? In this case the data from the main module is augmented in different modules for IPv4 and IPv6 unicast routing.

**Comment by jktjkt** [comment]
In the C++ wrapper there's no difference between creating terms and non-term nodes; just use `newPath` for this. Take a look at the test suite, especially the [`tests/data_node.cpp`](https://github.com/CESNET/libyang-cpp/blob/master/tests/data_node.cpp).

(Please reopen if there's anything missing.)
