### ISSUE TITLE
Feature request: Wrapper for lyd_compare_single and lyd_compare_siblings

### ISSUE THREAD

**Issue by rbu9fe** [CESNET/libyang-cpp#19]
As the title says the wrapper lacks support for `lyd_compare_single` and `lyd_compare_siblings` as the data node's `operator==` only compares whether the two nodes point to the very same item rather than comparing whether they have the same contents.
Is there a chance to get this functionality?

**Comment by rbu9fe** [comment]
Great! I guess I would prefer the symbolic approach, but I'm fine with whatever fits bests into the current design.

**Comment by syyyr** [comment]
Could also go with the "java" approach:
```cpp
if (node1.siblingsEqual(node2)) {
    // ...
}

if (node1.substreesEqual()) {
    // ...
}
```
It's easier to find methods like these through code completion (more than the `operator==` or the free function version IMHO).

It would also sort of follow the principle of how we wrap the functions - `foo(node, args...)` turns into `node.foo(args...)`.

Also, `lyd_compare_single` has a "Data compare options" argument. Would it be possible to specify this argument, if we were to use `operator==` version?

**Comment by syyyr** [comment]
Maybe I have missed that `.wholeTree()` is probably specifying the `LYD_COMPARE_FULL_RECURSION` flag... that would probably solve that (but idk about `LYD_COMPARE_DEFAULTS` or `LYD_COMPARE_OPAQ`. Anyway, the Java approach is still an option.

**Comment by rbu9fe** [comment]
Just curious, is there any progress on this?

**Comment by jktjkt** [comment]
How does https://gerrit.cesnet.cz/c/CzechLight/libyang-cpp/+/6829 look like?

**Comment by rbu9fe** [comment]
Looks nice to me!
