### ISSUE TITLE
New impacts with Libyang 2.2.8

### ISSUE THREAD

**Issue by Krisscut** [CESNET/libyang-cpp#22]
Hello there !

Just a heads-up, it seems with latest libyang release there are some breaking changes that needs adaption in the lib 

https://github.com/CESNET/libyang/releases/tag/v2.2.8
Changes are detailed in that document:

https://github.com/CESNET/libyang/blob/master/doc/transition_2_3.dox 

I had to make a few adaptations in my software, mostly around the log callback and replacing LYD_NEW_PATH_OUTPUT      by 
 LYD_NEW_VAL_OUTPUT but I guess there could be more impacts in **libyang-cpp**

**Comment by tbsuht** [comment]
An updates? :)

**Comment by jktjkt** [comment]
Yeah, sorry for this. It's a work in progress. You can follow the development [here](https://gerrit.cesnet.cz/q/project:CzechLight/libyang-cpp+is:open+label:Code-Review%252B2), and after clicking on the most recent one, there's a download button in there. Right now you can get the latest and greatest like this:
```
git fetch origin refs/changes/53/7353/6 && git checkout FETCH_HEAD
```

**Comment by jktjkt** [comment]
Done.
