### ISSUE TITLE
Support for libyang-cpp with commit https://github.com/CESNET/libyang/tree/b3d079fc37ac119f5a2a4a120b86d1c7102c3a08

### ISSUE THREAD

**Issue by srikanths1** [CESNET/libyang-cpp#24]
Hi, 

to use libyang-cpp, it has a dependancy on libyang branch which is based out of a private commit id, is there any plan to make the private commit available on libyang on official latest version? because of the dependancy, we are mandated to use older versions of libyang, sysrepo and netopeer2. Please update

**Comment by jktjkt** [comment]
Hello, it's just an older commit. If you checkout that repo (`libyang`) and do something like `git reset --hard b3d079fc37`, it will do the trick. It's basically the last version of "libyang v3" before an incompatible API change.

Alternatively, feel free to use the libyang-v3 work-in-progress bits from this repo (`libyang-cpp`), currently it's at d29365c. (There's no branch for that, though.) It will work with the latest `devel` of `libyang`.
