### ISSUE TITLE
Not described build switches? BUILD_TESTING, WITH_DOCS (by default, they seem to be on)

### ISSUE THREAD

**Issue by capiman** [CESNET/libyang-cpp#25]
BUILD_TESTING: dependency at least on doctest 2.3.6

WITH_DOCS: doxygen needed?

**Comment by jktjkt** [comment]
hello:
- `BUILD_TESTING` is a [standard CMake option](https://cmake.org/cmake/help/latest/module/CTest.html); it's just the way how "a lot" of projects which use CMake for configuration control building the documentation.
- `WITH_DOCS` is not as much standardized as the other one, but it still feels rather widely used to me.

I'm not sure what the question/suggestion is here; CMake's native features (something like `cmake -LH`) show a short description. What are you missing?

**Comment by capiman** [comment]
Thanks for the fast feedback!

I was building it and it aborted due to missing doctest and doxygen. Looking into CMakeLists.txt, I saw quickly what is needed.

Perhaps it would be helpful to list the 2 programs in 

https://github.com/CESNET/libyang-cpp/blob/master/README.md

under Dependencies ( https://github.com/CESNET/libyang-cpp#dependencies ) and mention the build switches?

**Comment by jktjkt** [comment]
Ah, right, indeed. How does [this patch](https://gerrit.cesnet.cz/c/CzechLight/libyang-cpp/+/7359) look to you?

**Comment by capiman** [comment]
This looks good, thank you!
