### ISSUE TITLE
Libyang CPP extension support for the latest version

### ISSUE THREAD

**Issue by svashok** [CESNET/libyang-cpp#26]
Hi,

In order to use CPP extension for libyang there is a dependency to use 4 months old commit tag of libyang. Can you please let me know if this dependency still exists, if yes when will this be addressed?

![image](https://github.com/user-attachments/assets/06635a2b-c219-4727-a485-8fc0edef28b6)

Thanks!

**Comment by jktjkt** [comment]
Current `master` of libyang-cpp indeed requires that older version of libyang. We have [newer code on Gerrit](https://gerrit.cesnet.cz/q/project:CzechLight%252Flibyang-cpp+status:open), it will be merged to master once we're ready. All of these patches are also available [through some special branches on GitHub](https://github.com/CESNET/libyang-cpp/tree/38e3399c99a82d3c0f693fb19ab1e1b3cd72aed9). If you have no need to stick with pre-libyang-v3, use that one, absolutely.

**Comment by jktjkt** [comment]
Done.

**Comment by rohanhiyer** [comment]
Hi,

As i understand, this is a patch available. This needs to be applied on which base code for now ?

Thanks

**Comment by jktjkt** [comment]
just use the latest master, you don’t have to apply any patches anymore
