### ISSUE TITLE
Add SOVERSION to the shared lib

### ISSUE THREAD

**Issue by gotthardp** [CESNET/libyang-cpp#3]
Would you please add SOVERSION to the shared library, just like libyang has (or somehow similarly)?
```cmake
set_target_properties(yang PROPERTIES VERSION ${LIBYANG_SOVERSION_FULL} SOVERSION ${LIBYANG_SOVERSION})
```
Yocto Linux reports a "QA issue" that there is none.

**Comment by jktjkt** [comment]
We might still make some backward-incompatible changes to both APIs and ABIs, so I think it might be cleaner to add this later on when we're ready to start taking compatibility seriously. The same applies to sysrepo-cpp.

**Comment by jktjkt** [comment]
`SOVERSION` is there now, thanks for the patience.
