### ISSUE TITLE
Missing export.h file 

### ISSUE THREAD

**Issue by ajaygoud-k** [CESNET/libyang-cpp#6]
Most of files in include/libyang-cpp have included export.h and that was missing .Can you help me with that.

**Comment by jktjkt** [comment]
You have to build and install this library, it's not a header-only thing. The `<libyang/export.h>` gets generated during the build:

https://github.com/CESNET/libyang-cpp/blob/f8a23f0abdb8989aae6bb6f9bd011d05bd8e482b/CMakeLists.txt#L64-L65

In your code which uses `libyang-cpp`, you're expected to use the usual pkg-config way of finding the includes and linking against the resulting `libyang-cpp`. This means that the library should be looked for in your target installation directory, not in the source tree, and not in the build tree.

**Comment by ajaygoud-k** [comment]
As you stated " you're expected to use the usual pkg-config way of finding the includes and linking against the resulting libyang-cpp ". so can i know what exactly im doing wrong and what i should be doing instead.

**Comment by jktjkt** [comment]
You have not said how you're building this library, or how you're trying to use it. The correct steps are to:
1) build the library via CMake,
2) install the library into some prefix,
3) look for the installed version of the library via pkg-config, which will use a file called `libyang-cpp.pc` which was created in step 2, to set up include paths and linking directories for your C++ compiler.

It's really straightforward; for the usage example see how `sysrepo-cpp` is doing this (look for `LIBYANG_CPP` in https://github.com/sysrepo/sysrepo-cpp/blob/master/CMakeLists.txt and see its full build script at https://github.com/sysrepo/sysrepo-cpp/blob/master/ci/build.sh).
