### ISSUE TITLE
Wrapper missing for lys_find_xpath_atoms

### ISSUE THREAD

**Issue by irfanHaslanded** [CESNET/libyang-cpp#9]
I was wondering if there is a plan to add wrappers for the remaining libyang api such as `lys_find_xpath_atoms`

**Comment by jktjkt** [comment]
We are not actively working on adding C++ bindings for all functions that are exported by `libyang`. We're happy to review patches which implement the missing functionality. If you need some help getting your first patch merged, just ask.

Looking at the docs, this function seems pretty low-level, so I'm curious: what do you need it for, btw?
